### PR TITLE
Change workflow to use a reusable workflow for building the Go release

### PR DESCRIPTION
**Pull request by webbnh**
## Changes introduced with this PR

Modify the build to use the `arcaflow-reusable-workflows/go_release.yaml` reusable workflow.

---
By contributing to this repository, I agree to the [contribution guidelines](https://github.com/arcalot/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by webbnh** [comment]
@jaredoconnell, the build appears to have run fine, but GH is still looking for a job from the old build (which isn't going to run, let alone report status), so, once this is approved, you'll need to use the Admin override to merge it.

**Review by dbutenhof — APPROVED** [review]

**Review by mfleader — APPROVED** [review]

**Comment by webbnh** [comment]
This PR is now back in draft awaiting https://github.com/arcalot/arcaflow-reusable-workflows/pull/17.

**Review by dbutenhof — APPROVED** [review]
Looks like it ought to be pretty straightforward ...

**Review by jaredoconnell — APPROVED** [review]

**Comment by jaredoconnell** [comment]
This appears to have been merged, but not closed due to a Github glitch.

**Pull request closed without merging**
